//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap African_Burger {
            get {
                object obj = ResourceManager.GetObject("African_Burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap baby_775503_640 {
            get {
                object obj = ResourceManager.GetObject("baby-775503_640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap baerlauch_hummus_652693_1 {
            get {
                object obj = ResourceManager.GetObject("baerlauch_hummus_652693_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bagels_mit_Frischkäse_und_Avocado {
            get {
                object obj = ResourceManager.GetObject("Bagels_mit_Frischkäse_und_Avocado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BBQ_Pulled_Sweet_Potato_Burger {
            get {
                object obj = ResourceManager.GetObject("BBQ_Pulled_Sweet_Potato_Burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap beef_wellington_smarter_5921 {
            get {
                object obj = ResourceManager.GetObject("beef_wellington_smarter_5921", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap biskuitteig_dinkelmehl_8863 {
            get {
                object obj = ResourceManager.GetObject("biskuitteig_dinkelmehl_8863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Butternut_Kürbis_Suppe {
            get {
                object obj = ResourceManager.GetObject("Butternut_Kürbis_Suppe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Carolyn_Cooking_Blog {
            get {
                object obj = ResourceManager.GetObject("Carolyn-Cooking-Blog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Collage_2021_06_28_15_59_41 {
            get {
                object obj = ResourceManager.GetObject("Collage 2021-06-28 15_59_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Collage_2021_06_28_15_59_411 {
            get {
                object obj = ResourceManager.GetObject("Collage 2021-06-28 15_59_411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cottage_pie_mit_fleisch_und_gemuese_gefuellt_33983 {
            get {
                object obj = ResourceManager.GetObject("cottage_pie_mit_fleisch_und_gemuese_gefuellt_33983", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filettopf {
            get {
                object obj = ResourceManager.GetObject("Filettopf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fisch_Burger {
            get {
                object obj = ResourceManager.GetObject("Fisch_Burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fischburger {
            get {
                object obj = ResourceManager.GetObject("Fischburger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap forellen_vom_grill_42191 {
            get {
                object obj = ResourceManager.GetObject("forellen_vom_grill_42191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frozen_joghurt_mit_himbeeren_448530 {
            get {
                object obj = ResourceManager.GetObject("frozen_joghurt_mit_himbeeren_448530", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap frucht_paprika_kurkuma_smoothie_660269 {
            get {
                object obj = ResourceManager.GetObject("frucht_paprika_kurkuma_smoothie_660269", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gebackene_Mettbrötchen {
            get {
                object obj = ResourceManager.GetObject("Gebackene_Mettbrötchen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gegrillte_schweinefilets_5295 {
            get {
                object obj = ResourceManager.GetObject("gegrillte_schweinefilets_5295", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gegrillte_zitronen_kartoffeln_36543 {
            get {
                object obj = ResourceManager.GetObject("gegrillte_zitronen_kartoffeln_36543", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gemuese_couscous_mit_haehnchen_39839 {
            get {
                object obj = ResourceManager.GetObject("gemuese_couscous_mit_haehnchen_39839", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gemuese_couscous_mit_rinderfrikadellen_655599 {
            get {
                object obj = ResourceManager.GetObject("gemuese_couscous_mit_rinderfrikadellen_655599", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gemuese_linsen_eintopf_mit_erbsen_661997 {
            get {
                object obj = ResourceManager.GetObject("gemuese_linsen_eintopf_mit_erbsen_661997", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gemüse_Burger {
            get {
                object obj = ResourceManager.GetObject("Gemüse_Burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap geschmorte_lammhaxen_smarter_5891 {
            get {
                object obj = ResourceManager.GetObject("geschmorte_lammhaxen_smarter_5891", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap grillkaese_halloumi_mit_wassermelone_56017 {
            get {
                object obj = ResourceManager.GetObject("grillkaese_halloumi_mit_wassermelone_56017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Grünkern_Burger {
            get {
                object obj = ResourceManager.GetObject("Grünkern_Burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap haehnchen_schnitzel_mit_nudeln_197493 {
            get {
                object obj = ResourceManager.GetObject("haehnchen_schnitzel_mit_nudeln_197493", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap haehnchenfleisch_wuerstchen_spiesse_mit_gemuese_35143 {
            get {
                object obj = ResourceManager.GetObject("haehnchenfleisch_wuerstchen_spiesse_mit_gemuese_35143", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap haehnchenschlegel_vom_grill_mit_kraeuterbutter_37083 {
            get {
                object obj = ResourceManager.GetObject("haehnchenschlegel_vom_grill_mit_kraeuterbutter_37083", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Haferflocken_Burger_mit_Rote_Bete_und_Walnüssen {
            get {
                object obj = ResourceManager.GetObject("Haferflocken_Burger_mit_Rote_Bete_und_Walnüssen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap himbeer_joghurt_eis_9025 {
            get {
                object obj = ResourceManager.GetObject("himbeer_joghurt_eis_9025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hirschgulasch_mit_schokolade_und_ofenmoehren_656927 {
            get {
                object obj = ResourceManager.GetObject("hirschgulasch_mit_schokolade_und_ofenmoehren_656927", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap holunderblueten_joghurt_eis_8783 {
            get {
                object obj = ResourceManager.GetObject("holunderblueten_joghurt_eis_8783", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hospitality_3793946_960_720 {
            get {
                object obj = ResourceManager.GetObject("hospitality-3793946_960_720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_info_9 {
            get {
                object obj = ResourceManager.GetObject("icon-info-9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_10_45_13 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_10_45_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_10_55_00 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_10_55_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_11_01_54 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_11_01_54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_11_57_00 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_11_57_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_12_13_40 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_12_13_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_12_21_16 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_12_21_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_12_32_51 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_12_32_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_12_44_54 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_12_44_54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_12_54_05 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_12_54_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_13_02_08 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_13_02_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_13_13_17 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_13_13_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_13_20_19 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_13_20_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_13_31_32 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_13_31_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_13_57_14 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_13_57_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_14_08_02 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_14_08_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_14_22_23 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_14_22_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_14_31_36 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_14_31_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_14_45_09 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_14_45_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_14_56_48 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_14_56_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_15_06_28 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_15_06_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_15_20_51 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_15_20_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_15_25_36 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_15_25_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_15_32_35 {
            get {
                object obj = ResourceManager.GetObject("Image_2021_07_10_15_32_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_18_39_23 {
            get {
                object obj = ResourceManager.GetObject("Image 2021-07-10 18.39.23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_18_391 {
            get {
                object obj = ResourceManager.GetObject("Image 2021-07-10 18.391", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_2021_07_10_18_392 {
            get {
                object obj = ResourceManager.GetObject("Image 2021-07-10 18.392", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap jighurt_brombeer_parfait_41785 {
            get {
                object obj = ResourceManager.GetObject("jighurt_brombeer_parfait_41785", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap joghurteis_mit_beeren_322641 {
            get {
                object obj = ResourceManager.GetObject("joghurteis_mit_beeren_322641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap joghurteis_mit_blaubeeren_321893 {
            get {
                object obj = ResourceManager.GetObject("joghurteis_mit_blaubeeren_321893", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap joghurteis_mit_schokotropfen_117265 {
            get {
                object obj = ResourceManager.GetObject("joghurteis_mit_schokotropfen_117265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kaeseomelett_mit_lachs_35281 {
            get {
                object obj = ResourceManager.GetObject("kaeseomelett_mit_lachs_35281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kalbsfilet_sizilianische_art_5567 {
            get {
                object obj = ResourceManager.GetObject("kalbsfilet_sizilianische_art_5567", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kalbsragout_kohlrabi_8089 {
            get {
                object obj = ResourceManager.GetObject("kalbsragout_kohlrabi_8089", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kalbsrahmgulasch_smarter_5577 {
            get {
                object obj = ResourceManager.GetObject("kalbsrahmgulasch_smarter_5577", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kalbsschnitzel_a_la_saltimbocca_7937 {
            get {
                object obj = ResourceManager.GetObject("kalbsschnitzel_a_la_saltimbocca_7937", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kalbsschnitzel_granatapfelsauce_5595 {
            get {
                object obj = ResourceManager.GetObject("kalbsschnitzel_granatapfelsauce_5595", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kuerbiskekse_668323 {
            get {
                object obj = ResourceManager.GetObject("kuerbiskekse_668323", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kurzrippensteak_vom_grill_39989 {
            get {
                object obj = ResourceManager.GetObject("kurzrippensteak_vom_grill_39989", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap labneh_670163 {
            get {
                object obj = ResourceManager.GetObject("labneh_670163", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lamm_curry_mit_pflaumen_668061 {
            get {
                object obj = ResourceManager.GetObject("lamm_curry_mit_pflaumen_668061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lammkeule_vom_grill_32359 {
            get {
                object obj = ResourceManager.GetObject("lammkeule_vom_grill_32359", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Leberkäse {
            get {
                object obj = ResourceManager.GetObject("Leberkäse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap leichtes_joghurteis_mit_honig_38181 {
            get {
                object obj = ResourceManager.GetObject("leichtes_joghurteis_mit_honig_38181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Like {
            get {
                object obj = ResourceManager.GetObject("Like", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Like_nottransparent {
            get {
                object obj = ResourceManager.GetObject("Like_nottransparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Linguine_Carbonara {
            get {
                object obj = ResourceManager.GetObject("Linguine_Carbonara", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap low_carb_pancakes_mit_banane_504119_1 {
            get {
                object obj = ResourceManager.GetObject("low_carb_pancakes_mit_banane_504119_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Meatballs {
            get {
                object obj = ResourceManager.GetObject("Meatballs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meerrettich_schnitzel_4935_1 {
            get {
                object obj = ResourceManager.GetObject("meerrettich_schnitzel_4935_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Möhren_Sesam_Burger_mit_Avocado {
            get {
                object obj = ResourceManager.GetObject("Möhren_Sesam_Burger_mit_Avocado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nudeln_mit_haehnchen_tomatensauce_159745 {
            get {
                object obj = ResourceManager.GetObject("nudeln_mit_haehnchen_tomatensauce_159745", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ofenkartoffeln_mit_brokkoli_655738 {
            get {
                object obj = ResourceManager.GetObject("ofenkartoffeln_mit_brokkoli_655738", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap orangen_lachs_mit_nussreis_448768_1 {
            get {
                object obj = ResourceManager.GetObject("orangen_lachs_mit_nussreis_448768_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paprika_rindfleischpfanne_448298 {
            get {
                object obj = ResourceManager.GetObject("paprika_rindfleischpfanne_448298", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pasta_mit_gruenem_spargel_tomaten_und_pinienkernen_42143_1 {
            get {
                object obj = ResourceManager.GetObject("pasta_mit_gruenem_spargel_tomaten_und_pinienkernen_42143_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pasta_mit_Hackfleisch_Kräuter_Soße {
            get {
                object obj = ResourceManager.GetObject("Pasta_mit_Hackfleisch_Kräuter_Soße", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pexels_ella_olsson_1640777__1_ {
            get {
                object obj = ResourceManager.GetObject("pexels_ella_olsson_1640777__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pexels_horizon_content_3915857 {
            get {
                object obj = ResourceManager.GetObject("pexels_horizon_content_3915857", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pexels_jane_d_1092730 {
            get {
                object obj = ResourceManager.GetObject("pexels_jane_d_1092730", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pexels_jonathan_borba_2983101 {
            get {
                object obj = ResourceManager.GetObject("pexels_jonathan_borba_2983101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pexels_maarten_van_den_heuvel_2284166 {
            get {
                object obj = ResourceManager.GetObject("pexels-maarten-van-den-heuvel-2284166", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pexels_ponyo_sakana_4193872 {
            get {
                object obj = ResourceManager.GetObject("pexels_ponyo_sakana_4193872", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pexels_valeria_boltneva_1199960 {
            get {
                object obj = ResourceManager.GetObject("pexels-valeria-boltneva-1199960", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pexels_valeria_boltneva_842571 {
            get {
                object obj = ResourceManager.GetObject("pexels_valeria_boltneva_842571", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pizza_3010062_1280 {
            get {
                object obj = ResourceManager.GetObject("pizza-3010062_1280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pizzateig {
            get {
                object obj = ResourceManager.GetObject("pizzateig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pulled_Jackfruit_Burger_mit_Rotkohlsalat {
            get {
                object obj = ResourceManager.GetObject("Pulled_Jackfruit_Burger_mit_Rotkohlsalat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pytt_i_panna_664817 {
            get {
                object obj = ResourceManager.GetObject("pytt_i_panna_664817", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap registration_4226949_640 {
            get {
                object obj = ResourceManager.GetObject("registration-4226949_640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reispfanne_1426 {
            get {
                object obj = ResourceManager.GetObject("reispfanne_1426", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rhabarber_Reis_mit_Hähnchen___Kräuterjoghurt {
            get {
                object obj = ResourceManager.GetObject("Rhabarber_Reis_mit_Hähnchen___Kräuterjoghurt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rindergulasch_mit_Kräutern {
            get {
                object obj = ResourceManager.GetObject("Rindergulasch_mit_Kräutern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rotkrautrouladen_mit_Hackfüllung_dazu_Kartoffeln {
            get {
                object obj = ResourceManager.GetObject("Rotkrautrouladen_mit_Hackfüllung_dazu_Kartoffeln", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rinderfilet_kraeutergewuerzmantel_5631 {
            get {
                object obj = ResourceManager.GetObject("rinderfilet_kraeutergewuerzmantel_5631", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rindfleisch_wok_5617 {
            get {
                object obj = ResourceManager.GetObject("rindfleisch_wok_5617", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rouladen_marokkanische_art_5133 {
            get {
                object obj = ResourceManager.GetObject("rouladen_marokkanische_art_5133", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Roulladen {
            get {
                object obj = ResourceManager.GetObject("Roulladen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Schnelle_Gulaschsuppe {
            get {
                object obj = ResourceManager.GetObject("Schnelle_Gulaschsuppe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap schweinefilet_pfanne_mit_gemuese_33385 {
            get {
                object obj = ResourceManager.GetObject("schweinefilet_pfanne_mit_gemuese_33385", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap schweinerueckenbraten_5907 {
            get {
                object obj = ResourceManager.GetObject("schweinerueckenbraten_5907", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap seeteufel_spinat_paeckchen_653619 {
            get {
                object obj = ResourceManager.GetObject("seeteufel_spinat_paeckchen_653619", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sesamenoodle {
            get {
                object obj = ResourceManager.GetObject("Sesamenoodle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Smartes_Rindergulasch_Grundrezept {
            get {
                object obj = ResourceManager.GetObject("Smartes_Rindergulasch_Grundrezept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Spaghetti {
            get {
                object obj = ResourceManager.GetObject("Spaghetti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap spareribs_vom_grill_107535 {
            get {
                object obj = ResourceManager.GetObject("spareribs_vom_grill_107535", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap spargel_klassisch_mit_entenbrust_660237 {
            get {
                object obj = ResourceManager.GetObject("spargel_klassisch_mit_entenbrust_660237", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap speck_zucchini_roellchen_mit_feta_fuellung_110115 {
            get {
                object obj = ResourceManager.GetObject("speck_zucchini_roellchen_mit_feta_fuellung_110115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Spinat_Bacon_Burger_mit_Roter_Bet {
            get {
                object obj = ResourceManager.GetObject("Spinat_Bacon_Burger_mit_Roter_Bet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Spinat_Crespelle_mit_Schinkenwurst {
            get {
                object obj = ResourceManager.GetObject("Spinat_Crespelle_mit_Schinkenwurst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Steakburger_mit_Rotkohl {
            get {
                object obj = ResourceManager.GetObject("Steakburger_mit_Rotkohl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap steaks_salzbett_5629 {
            get {
                object obj = ResourceManager.GetObject("steaks_salzbett_5629", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap suesskartoffelsalat_650483 {
            get {
                object obj = ResourceManager.GetObject("suesskartoffelsalat_650483", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sushi_Burger {
            get {
                object obj = ResourceManager.GetObject("Sushi_Burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tandoori_lammgeschnetzeltes_6153 {
            get {
                object obj = ResourceManager.GetObject("tandoori_lammgeschnetzeltes_6153", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tofu_Burger_mit_Hummus {
            get {
                object obj = ResourceManager.GetObject("Tofu_Burger_mit_Hummus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tofu_Polenta_Burger {
            get {
                object obj = ResourceManager.GetObject("Tofu_Polenta_Burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tortellini_auflauf_mit_schinken_und_fruehlingszwiebeln_454276 {
            get {
                object obj = ResourceManager.GetObject("tortellini_auflauf_mit_schinken_und_fruehlingszwiebeln_454276", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tortellini_mit_Ricotta__Spinat___Walnüssen {
            get {
                object obj = ResourceManager.GetObject("Tortellini_mit_Ricotta__Spinat___Walnüssen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Trüffel_Käse_Girasoli_mit_Zucchinisalat {
            get {
                object obj = ResourceManager.GetObject("Trüffel_Käse_Girasoli_mit_Zucchinisalat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ueberbackene_kalbsschnitzel_5599 {
            get {
                object obj = ResourceManager.GetObject("ueberbackene_kalbsschnitzel_5599", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vegane_Burger_Buns {
            get {
                object obj = ResourceManager.GetObject("Vegane_Burger_Buns", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vegane_linsen_pasta_mit_pesto_rosso_und_rucola_656528 {
            get {
                object obj = ResourceManager.GetObject("vegane_linsen_pasta_mit_pesto_rosso_und_rucola_656528", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vegane_Süßkartoffel_Burger {
            get {
                object obj = ResourceManager.GetObject("Vegane_Süßkartoffel_Burger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Veganer_Cheeseburger_mit_Black_Bean_Patty {
            get {
                object obj = ResourceManager.GetObject("Veganer_Cheeseburger_mit_Black_Bean_Patty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vegetarisches_linsen_chili_mit_reis_653881 {
            get {
                object obj = ResourceManager.GetObject("vegetarisches_linsen_chili_mit_reis_653881", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zebrakuchen {
            get {
                object obj = ResourceManager.GetObject("Zebrakuchen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
